version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../:/var/www
    depends_on:
      - mysql
      - php
      - phpmyadmin

  php:
    build:
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: serverName=Docker

  mysql:
    platform: linux/x86_64
    image: mysql:8
    container_name: test_db
    ports:
      - "3306:3306"
    env_file:
      - ./env/mysql.env
    volumes:
      - ./db_data:/var/lib/mysql

  phpmyadmin:
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    env_file:
      - ./env/phpMyAdmin.env
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  db_data:
